spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.185.42:3306/ccjt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: yaoqianguan_app
    password: yqg!123321
server:
  port: 8081
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true